language: node_js
sudo: required
before_install:
- "./.travis_before_install.sh"
script:
  - yarn test:node
node_js:
  - "node"
cache:
  yarn: true  
notifications:
  slack:
    secure: s1UeMCWmI/IIWllmazf428HX1tqfGOo4bsACq4uvofGxxNuSMb6MfCLL+KzIl2CVyD1sLhDfW4GOBj+Ih+USwxgly4lFfT/ROdrPaqCNtUYvseGXkR7YfrS7GCAbtTrJuHpNC+WAS5lRMLopIQSaQpPQQQ8IEi0Uc52syUhhk05iQmMcveTcdYHgDfl3jgjM6rwlSaJGG7S8F7bDiR3sQ3hDNlMeDk+6BW3vatVSTljPGmvltdOdCdU51kcA494dxMs8wtkA92bi9EUhOHa9jQbwoFNRyP7b//ZJy09rfpaGTE3VbBvdl9TEGSV+mJ9dqUqaxRiLJwfKp5GgAA3TNwrwTBMml9oLPdnFfrYwW2OImGxmZeLbGumU9qEr8lMDrbRo9cxpkeS2zSBKu3RHm0krjWIt2m8YrpHX0820aN5TRr/lGDVXHbOCls/NMYYRAdcCeQfIotOQOXaf1+76iH4Z5qm5RnTt4YvGMXvcRyGOfafW82LEuzV9HtCC1JCV84iv4XzqvfIk3AMPveUJqSA3YCsFbUI3x8SJFHQ6GuajHo5WjmS0YBpXskvWBl9SNON6ewOVSRG25Z50A5FbKrE0t1VKFPC/2KWUqcwxW4R71EyoBATj1TS14RPmiuc2CUAu2ysg039bisY+rZ+7Rz+eFTyfAFuCNCgrugr3udw=
