language: node_js
sudo: required
node_js:
  - node
go:
  - 1.10.2
cache:
  yarn: true
before_install:
  - "./.travis_before_install.sh"
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn install
script:
  - "./.travis_e2e_test.sh"
notifications:
  slack:
    secure: s1UeMCWmI/IIWllmazf428HX1tqfGOo4bsACq4uvofGxxNuSMb6MfCLL+KzIl2CVyD1sLhDfW4GOBj+Ih+USwxgly4lFfT/ROdrPaqCNtUYvseGXkR7YfrS7GCAbtTrJuHpNC+WAS5lRMLopIQSaQpPQQQ8IEi0Uc52syUhhk05iQmMcveTcdYHgDfl3jgjM6rwlSaJGG7S8F7bDiR3sQ3hDNlMeDk+6BW3vatVSTljPGmvltdOdCdU51kcA494dxMs8wtkA92bi9EUhOHa9jQbwoFNRyP7b//ZJy09rfpaGTE3VbBvdl9TEGSV+mJ9dqUqaxRiLJwfKp5GgAA3TNwrwTBMml9oLPdnFfrYwW2OImGxmZeLbGumU9qEr8lMDrbRo9cxpkeS2zSBKu3RHm0krjWIt2m8YrpHX0820aN5TRr/lGDVXHbOCls/NMYYRAdcCeQfIotOQOXaf1+76iH4Z5qm5RnTt4YvGMXvcRyGOfafW82LEuzV9HtCC1JCV84iv4XzqvfIk3AMPveUJqSA3YCsFbUI3x8SJFHQ6GuajHo5WjmS0YBpXskvWBl9SNON6ewOVSRG25Z50A5FbKrE0t1VKFPC/2KWUqcwxW4R71EyoBATj1TS14RPmiuc2CUAu2ysg039bisY+rZ+7Rz+eFTyfAFuCNCgrugr3udw=
  slackn:
    secure: JsMq3RNe2mHPKfhdSI8fV1xs4OJVdgbd3g6/LmFQFMSk8FyrqcbtT6q1cTU1XrYupAhdXvtqfp4JqOHrFJCRwFMyZz3F5Yk2bP/Gu4wKtVVCPiJJMzATdrOs7bz87jXNyOAglAEGo73Mn3rIxkFBX9QrFNNJN/wyQ7BGE194J2d7+QRLq/5Ievw74NAz1DFVl26Qr38nfs3f2e0bXkXViV0dGAf3X/TbrXJyRFmTh4gaMqXCKq8EHC08WBtQOA97+jSYjYjuSgkA00F42Nhqn7SaVMe77P1y1IhjRpUb/251MTT9JQc3lN8z07CFjJDeEmCBy3jkSzuFM+bQI1uq0ybwpTSBPxS9VMaFwX0DbgWb+Ui7YaNcSIEfYHpAVoWq86ljq5yNAlgQYTUtIHoSKAA0VIKZcwbFgn9ThUhJWjsGPuY4AaiH2K91XrkfJQOSgSu1M6ZzrhttqbCXwO7lNvfv22/wc8Y1SZgNYj7E+iw/NbbyQshAoqU5SqReTR/v17v/+blxdMaNjpcnxJb4z1L8LCa1erkKzEZ7mGAZFOElitSTKwO+vwvLPC5UM2PzkLDJVqu/YWpYF5hT5ONfzWH0e8MPr8HvNNmpKq7sb1KcW4ov3ug0ePqxq17JO58IUq9sCw+3mqKItlC5sygaoorJ25ZANX8HdWCdYw0gRTg=
addons:
  apt:
    packages:
      - xvfb